### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit/sandcastle#85]
As we can see in https://github.com/cockpit-project/cockpit-ostree/pull/31#issuecomment-731598411, the npm fails due to the permission of the `.npm` directory.

What about rebuilding the image?

Or, doing that `chown` command during startup of the container?

**Comment by jpopelka** [comment]
> What about rebuilding the image?
> Or, doing that `chown` command during startup of the container?

I think neither of those would work.

```
$ docker run -ti --rm -u 123456 usercont/sandcastle bash
$ npm install xyz
npm ERR!   sudo chown -R 123456:0 "/.npm"
$ ls -la /.npm
ls: cannot access '/.npm': No such file or directory
$ echo $HOME
/
```

The `npm` command tries to access `$HOME/.npm`, but given the `$HOME` is `/` it accesses `/.npm`.

After adding `RUN mkdir /.npm && chmod a+rwx /.npm/` into Dockerfile I saw
`npm ERR! Error: EACCES: permission denied, access '/src'`
and after adding `RUN chmod a+rwx /src/` I got
`npm update check failed, try sudo chown -R $USER:$(id -gn $USER) /.config`
so that's probably not the way and I think we need something like [this](https://github.com/packit/packit-service/blob/master/files/setup_env_in_openshift.sh) when we start the container.
```
